import { Inter } from "next/font/google";
import React from "react";
import Image from "next/image";
import "./globals.css";
import Head from "next/head";
import Footer from "../../components/Footer"
import Navbar from "../../components/Navbar";
import { CrowdFundingProvider } from "../../context/CrowdFunding";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Free Crowdfunding in India",
  description: "Generated by create next app",
  imageUrl: "/saathi-logo.jpg", // Replace this with the URL of your image
};

export default function RootLayout({ children }) {

  return (

    
    <CrowdFundingProvider>
    <html lang="en">
    <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
          <meta property="og:title" content={metadata.title} />
          <meta property="og:description" content={metadata.description} />
          <meta property="og:image" content="/saathi-logo.jpg" />
        </Head>

      <body className={inter.className}>
        

         
        {children}
        <Footer id="Contact Us"/>
      </body>
      
    </html>
    </CrowdFundingProvider>
  );
}
