import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";
import Footer from "../../components/Footer"
import Navbar from "../../components/Navbar";
import { CrowdFundingProvider } from "../../context/CrowdFunding";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  

  return (
    <CrowdFundingProvider>
    <html lang="en">
     
      <body className={inter.className}>
        
         <Navbar/>
         
        {children}
        <Footer id="Contact Us"/>
      </body>
      
    </html>
    </CrowdFundingProvider>
  );
}
